"use client";

import { redirect, usePathname } from "next/navigation";
import { useEffect } from "react";
import InterviewListSkeleton from "./all/_components/interview-list-skelaton";

const Page = () => {
  // const user = await getCurrentUser();
  // // Redirect to / as they are not authenticated
  // if (!user) {
  //   return redirect("/sign-in");
  // }

  const pathame = usePathname();

  useEffect(() => {
    if (pathame.startsWith("/interview")) redirect("/interview/all");
  }, [pathame]);

  return (
    <>
      <InterviewListSkeleton />
      {/* <h3 className="mb-4">AI Interview Generation</h3>
      <p className="text-muted-foreground text-base leading-relaxed mb-6">
        Get a tailored interview generated by our AI by sharing key details like
        job role, required skills, experience level, and tone (e.g., casual,
        professional, technical). You can ask things like: <br />
        <span className="italic">
          &quot; Create a technical interview for a React Developer with 2 years
          with SDE1 role, of MERN Stack &quot;
        </span>{" "}
        or{" "}
        <span className="italic">
          &quot;Generate 5 analytical questions for a Data Scientist
          interview.&quot;
        </span>
        The AI is already trained so the more precise your input is, the better
        the interview output!
      </p>
      <Agent
        userName={user?.name ?? ""}
        userId={user?.id ?? ""}
        type="generate"
      /> */}
    </>
  );
};

export default Page;
