// import Agent from "@/components/Agent";
// import { getCurrentUser } from "@/lib/actions/auth.action";
// import React from "react";

// const Page = async () => {
//   const user = await getCurrentUser();

//   return (
//     <>
//       <h3 className="mb-4">AI Interview Generation</h3>
//       <p className="text-muted-foreground text-base leading-relaxed mb-6">
//         Get a tailored interview generated by our AI by sharing key details like
//         job role, required skills, experience level, and tone (e.g., casual,
//         professional, technical). You can ask things like: <br />
//         <span className="italic">
//           &quot; Create a technical interview for a React Developer with 2 years
//           with SDE1 role, of MERN Stack &quot;
//         </span>{" "}
//         or{" "}
//         <span className="italic">
//           &quot;Generate 5 analytical questions for a Data Scientist
//           interview.&quot;
//         </span>
//         The AI is already trained so the more precise your input is, the better
//         the interview output!
//       </p>
//       <Agent
//         userName={user?.name ?? ""}
//         userId={user?.id ?? ""}
//         type="generate"
//       />
//     </>
//   );
// };

// export default Page;

import type { Metadata } from "next"
import AIInterviewCreation from "@/components/interviews/creation/ai-interview-creation"

export const metadata: Metadata = {
  title: "AI-Assisted Interview Creation | AI Voice Interview Platform",
  description: "Create a new interview with the help of our AI assistant",
}

export default function AIInterviewCreationPage() {
  return (
    <div className="container mx-auto py-8 px-4">
      <h1 className="text-3xl font-bold mb-2">AI-Assisted Interview Creation</h1>
      <p className="text-muted-foreground mb-8">
        Our AI assistant will guide you through creating the perfect interview
      </p>

      <AIInterviewCreation />
    </div>
  )
}
