export const programmingLogosList = [
  { value: "JavaScript", label: "JavaScript", icon: "/TechIcons/js.png" },
  { value: "Python", label: "Python", icon: "/TechIcons/python.png" },
  { value: "Java", label: "Java", icon: "/TechIcons/java.png" },
  { value: "C#", label: "C#", icon: "/TechIcons/c_sharp.png" },
  { value: "C++", label: "C++", icon: "/TechIcons/c_plus.png" },
  { value: "Swift", label: "Swift", icon: "/TechIcons/swift.png" },
  { value: "TypeScript", label: "TypeScript", icon: "/TechIcons/typescript.png" },
  { value: "HTML", label: "HTML", icon: "/TechIcons/html_5.png" },
  { value: "CSS", label: "CSS", icon: "/TechIcons/css_3.png" },
  { value: "React", label: "React", icon: "/TechIcons/atom.png" },
  { value: "Angular", label: "Angular", icon: "/TechIcons/Angular.png" },
  { value: "Vue.js", label: "Vue.js", icon: "/TechIcons/vue.png" },
  { value: "Ruby", label: "Ruby", icon: "/TechIcons/ruby.png" },
  { value: "Ruby on Rails", label: "Ruby on Rails", icon: "/TechIcons/rails.png" },
  { value: "Node.js", label: "Node.js", icon: "/TechIcons/nodejs.png" },
  { value: "Express.js", label: "Express.js", icon: "/TechIcons/express-js.png" },
  { value: "Django", label: "Django", icon: "/TechIcons/django.png" },
  { value: "Flask", label: "Flask", icon: "/TechIcons/flask.png" },
  { value: "Spring Boot", label: "Spring Boot", icon: "/TechIcons/spring-boot.png" },
  { value: "ASP.NET", label: "ASP.NET", icon: "/TechIcons/aspdotnet.png" },
  { value: "GraphQL", label: "GraphQL", icon: "/TechIcons/graphql.svg" },
  { value: "SQL", label: "SQL", icon: "/TechIcons/sql-server.png" },
  { value: "NoSQL", label: "NoSQL", icon: "/TechIcons/NoSql.png" },
  { value: "MongoDB", label: "MongoDB", icon: "/TechIcons/mongodb.svg" },
  { value: "MySQL", label: "MySQL", icon: "/TechIcons/mysql.svg" },
  { value: "PostgreSQL", label: "PostgreSQL", icon: "/TechIcons/postgresql.svg" },
  { value: "Git", label: "Git", icon: "/TechIcons/git.png" },
  { value: "GitHub", label: "GitHub", icon: "/TechIcons/github.png" },
  { value: "GitLab", label: "GitLab", icon: "/TechIcons/gitlab.png" },
  { value: "JIRA", label: "JIRA", icon: "/TechIcons/jira.png" },
  { value: "Agile", label: "Agile", icon: "/TechIcons/agile.png" },
  { value: "Scrum", label: "Scrum", icon: "/TechIcons/scrum.png" },
  { value: "Kanban", label: "Kanban", icon: "/TechIcons/kanban.png" },
  { value: "RESTful APIs", label: "RESTful APIs", icon: "/TechIcons/api.png" },
  { value: "AWS", label: "AWS", icon: "/TechIcons/aws.svg" },
  { value: "Azure", label: "Azure", icon: "/TechIcons/azure.svg" },
  { value: "GCP", label: "Google Cloud Platform (GCP)", icon: "/TechIcons/google-cloud.svg" },
  { value: "Docker", label: "Docker", icon: "/TechIcons/docker.png" },
  { value: "Kubernetes", label: "Kubernetes", icon: "/TechIcons/kubernets.svg" },
  { value: "CI/CD", label: "Continuous Integration/Deployment", icon: "/TechIcons/cicd.png" },
  { value: "Jenkins", label: "Jenkins", icon: "/TechIcons/jenkins.svg" },
  { value: "Travis CI", label: "Travis CI", icon: "/TechIcons/travis.svg" },
  { value: "CircleCI", label: "CircleCI", icon: "/TechIcons/circleci.png" },
  { value: "JWT", label: "JWT", icon: "/TechIcons/jwt.png" },
  { value: "OAuth", label: "OAuth", icon: "/TechIcons/Oauth.svg" },
  { value: "Web Security", label: "Web Security", icon: "/TechIcons/web.png" },
  { value: "Cybersecurity", label: "Cybersecurity", icon: "/TechIcons/cyber-security.png" },
  { value: "Unit Testing", label: "Unit Testing", icon: "/TechIcons/unitTesting.png" },
  { value: "Integration Testing", label: "Integration Testing", icon: "/TechIcons/integrationTesting.png" },
  { value: "Redux", label: "Redux", icon: "/TechIcons/redux-original.svg" },
  { value: "Webpack", label: "Webpack", icon: "/TechIcons/webpack-plain.svg" },
  { value: "Babel", label: "Babel", icon: "/TechIcons/Babel.png" },
  { value: "Linux", label: "Linux", icon: "/TechIcons/linux-logo.png" },
  { value: "Windows Server", label: "Windows Server", icon: "/TechIcons/windowsServer.png" },
  { value: "Shell Scripting", label: "Shell Scripting", icon: "/TechIcons/shellScripting.png" },
  { value: "Bash", label: "Bash", icon: "/TechIcons/bash.png" },
  { value: "PowerShell", label: "PowerShell", icon: "/TechIcons/powershell.png" },
  { value: "Machine Learning", label: "Machine Learning", icon: "/TechIcons/machineLearning.png" },
  { value: "AI", label: "Artificial Intelligence", icon: "/TechIcons/ai.png" },
  { value: "Blockchain", label: "Blockchain", icon: "/TechIcons/blockchain.png" },
  { value: "DevOps", label: "DevOps", icon: "/TechIcons/devops.png" },
  { value: "DSA", label: "Data Structures", icon: "/TechIcons/dataStructures.png" },
  { value: "Algorithms", label: "Algorithms", icon: "/TechIcons/algorithm.png" },
  { value: "Design Patterns", label: "Design Patterns", icon: "/TechIcons/designPattern.png" },
  { value: "Software Architecture", label: "Software Architecture", icon: "/TechIcons/softwareArchitecture.png" },
  { value: "Static Code Analysis", label: "Static Code Analysis", icon: "/TechIcons/staticCodeAnalysis.png" },
  { value: "Performance Optimization", label: "Performance Optimization", icon: "/TechIcons/optimization.svg" },
  { value: "State Management", label: "State Management", icon: "/TechIcons/stateManagement.png" },
  { value: "Responsive Design", label: "Responsive Design", icon: "/TechIcons/responsiveDesign.png" },
  { value: "Accessibility", label: "Accessibility", icon: "/TechIcons/Accessibility.png" },
  { value: "Version Control", label: "Version Control", icon: "/TechIcons/version-control.png" },
  { value: "Code Review", label: "Code Review", icon: "/TechIcons/code-review.png" },
  { value: "Agile Development", label: "Agile Development", icon: "/TechIcons/agileDevelopment.png" },
  { value: "Problem Solving", label: "Problem Solving", icon: "/TechIcons/problem-solving.png" },
  { value: "Critical Thinking", label: "Critical Thinking", icon: "/TechIcons/thinking.png" },
  { value: "Collaboration", label: "Collaboration", icon: "/TechIcons/partners.png" },
  { value: "Communication", label: "Communication", icon: "/TechIcons/communication.png" },
  { value: "Microservices Architecture", label: "Microservices Architecture", icon: "/TechIcons/microservices.png" },
  { value: "Containerization", label: "Containerization", icon: "/TechIcons/containerization.png" },
];

