import { Interview } from "@/types/profile";

export const customPasswordFeedbackMap: { [key: string]: string } = {
  "Add another word or two. Uncommon words are better.":
    "Make your password longer using uncommon words.",
  "No need for symbols, digits, or uppercase letters":
    "You can use symbols, digits, and uppercase letters to make your password stronger.",
  "Use a few words, avoid common phrases":
    "Try using unrelated words or a passphrase that's hard to guess.",
  "Straight rows of keys are easy to guess":
    "Avoid keyboard patterns like 'qwerty' or 'asdf'.",
  "Short passwords are easy to guess":
    "Use at least 8 characters to strengthen your password.",
  "Common names and surnames are easy to guess":
    "Avoid using common names or words.",
  "Names and surnames by themselves are easy to guess":
    "Try adding a mix of characters instead of just names.",
  'Repeats like "aaa" are easy to guess':
    "Avoid repeating the same characters.",
  "Sequences like abc or 6543 are easy to guess":
    "Avoid number or letter sequences like '123' or 'abc'.",
  "Recent years are easy to guess":
    "Avoid using recent years or your birth year.",
  "Dates are often easy to guess": "Avoid using calendar dates like birthdays.",
  "This is a top-10 common password":
    "This password is too common. Try something more unique.",
  "This is a top-100 common password":
    "This password is still very common. Make it stronger.",
  "This is similar to a commonly used password":
    "Your password is too similar to common ones. Try something unique.",
  "A word by itself is easy to guess":
    "Try combining multiple words and adding special characters.",
};

export const sampleInterviews: Interview[] = [
  {
    title: "Software Engineer",
    companyName: "TechCorp",
    companyLogo: "", // optional, empty for now
    level: "Medium",
    category: "Technical",
    type: "Coding",
    coding: true,
    completed: true,
    date: {
      interviewTimming: "future",
      avialabilityDuration: "limited",
      scheduledDate: "2025-05-21T18:30:00.000Z",
      durationPeriod: 20,
    },
    techStack: ["JavaScript", "React", "Node.js"],
    description:
      "Seeking a software engineer expert with deep experience in React, TypeScript, and UI/UX best practices.",
    durationLimit: 30,
    numberOfQuestions: 5,
    questions: [
      { question: "Explain the virtual DOM and its benefits", expectedAnswer: "" },
      { question: "How do you handle performance optimization in React apps", expectedAnswer: "" },
    ],
    invitedCandidates: ["candidate1", "candidate2"],
    createdAt: "2025-05-16T14:45:19.656Z",
    userId: "K3dQ4dvgJjVkf48XyeEqSC6nmd53",
  },

  {
    title: "Frontend Developer",
    companyName: "InnovateX",
    companyLogo: "",
    level: "Easy",
    category: "Technical",
    type: "Coding",
    coding: true,
    completed: false,
    date: {
      interviewTimming: "future",
      avialabilityDuration: "limited",
      scheduledDate: "2025-06-01T10:00:00.000Z",
      durationPeriod: 15,
    },
    techStack: ["HTML", "CSS", "JavaScript"],
    description: "Looking for a frontend developer with strong skills in HTML5, CSS3, and JavaScript.",
    durationLimit: 20,
    numberOfQuestions: 3,
    questions: [
      { question: "What is the CSS box model?", expectedAnswer: "" },
      { question: "Explain event delegation in JavaScript.", expectedAnswer: "" },
    ],
    invitedCandidates: [],
    createdAt: "2025-05-20T10:00:00.000Z",
    userId: "05zA4adRRvcFofNuZZooCVKbUEc2",
  },

  {
    title: "Product Manager",
    companyName: "GlobalTech",
    companyLogo: "",
    level: "Expert",
    category: "Non Technical",
    type: "Mix",
    coding: false,
    completed: true,
    date: {
      interviewTimming: "future",
      avialabilityDuration: "permanent",
      scheduledDate: null,
      durationPeriod: undefined,
    },
    techStack: [],
    description: "Experienced Product Manager required for managing agile teams.",
    durationLimit: 45,
    numberOfQuestions: 4,
    questions: [{ question: "Describe your experience with agile methodologies.", expectedAnswer: "" }],
    invitedCandidates: ["candidate3"],
    createdAt: "2025-05-15T09:00:00.000Z",
    userId: "VHfc0GTBNOYh0eJ9kV1BlQwaZi32",
  },

  {
    title: "Data Scientist",
    companyName: "DataWorks",
    companyLogo: "",
    level: "Hard",
    category: "Technical",
    type: "Coding",
    coding: true,
    completed: false,
    date: {
      interviewTimming: "future",
      avialabilityDuration: "limited",
      scheduledDate: "2025-06-10T09:00:00.000Z",
      durationPeriod: 30,
    },
    techStack: ["Python", "R", "SQL"],
    description: "Looking for a data scientist with expertise in machine learning algorithms.",
    durationLimit: 60,
    numberOfQuestions: 6,
    questions: [{ question: "Explain overfitting in machine learning.", expectedAnswer: "" }],
    invitedCandidates: ["candidate4", "candidate5"],
    createdAt: "2025-05-18T11:20:00.000Z",
    userId: "c3IVbqAf4xNLDO30E6atv0MBoaY2",
  },

  {
    title: "UX Designer",
    companyName: "CreativeLabs",
    companyLogo: "",
    level: "Medium",
    category: "Behavioral",
    type: "Voice",
    coding: false,
    completed: true,
    date: {
      interviewTimming: "future",
      avialabilityDuration: "limited",
      scheduledDate: "2025-05-25T13:00:00.000Z",
      durationPeriod: 10,
    },
    techStack: ["Figma", "Sketch"],
    description: "Seeking a UX designer with a strong portfolio and user-centric design philosophy.",
    durationLimit: 40,
    numberOfQuestions: 5,
    questions: [{ question: "How do you approach user research?", expectedAnswer: "" }],
    invitedCandidates: ["candidate6"],
    createdAt: "2025-05-17T08:30:00.000Z",
    userId: "c3IVbqAf4xNLDO30E6atv0MBoaY2",
  },

  {
    title: "Backend Developer",
    companyName: "CloudNet",
    companyLogo: "",
    level: "Expert",
    category: "Technical",
    type: "Coding",
    coding: true,
    completed: false,
    date: {
      interviewTimming: "future",
      avialabilityDuration: "limited",
      scheduledDate: "2025-06-05T11:30:00.000Z",
      durationPeriod: 25,
    },
    techStack: ["Node.js", "Express", "MongoDB"],
    description: "Looking for a backend developer with experience in RESTful APIs and microservices.",
    durationLimit: 35,
    numberOfQuestions: 5,
    questions: [{ question: "Explain REST and its principles.", expectedAnswer: "" }],
    invitedCandidates: ["candidate7", "candidate8"],
    createdAt: "2025-05-19T14:50:00.000Z",
    userId: "VHfc0GTBNOYh0eJ9kV1BlQwaZi32",
  },

  {
    title: "DevOps Engineer",
    companyName: "BuildIt",
    companyLogo: "",
    level: "Medium",
    category: "Technical",
    type: "Mix",
    coding: false,
    completed: true,
    date: {
      interviewTimming: "future",
      avialabilityDuration: "permanent",
      scheduledDate: null,
      durationPeriod: undefined,
    },
    techStack: ["AWS", "Docker", "Kubernetes"],
    description: "Experienced DevOps engineer needed for infrastructure automation.",
    durationLimit: 40,
    numberOfQuestions: 4,
    questions: [{ question: "What is CI/CD and why is it important?", expectedAnswer: "" }],
    invitedCandidates: ["candidate9"],
    createdAt: "2025-05-22T12:00:00.000Z",
    userId: "05zA4adRRvcFofNuZZooCVKbUEc2",
  },

  {
    title: "Marketing Specialist",
    companyName: "BrandMasters",
    companyLogo: "",
    level: "Easy",
    category: "Non Technical",
    type: "Voice",
    coding: false,
    completed: false,
    date: {
      interviewTimming: "future",
      avialabilityDuration: "limited",
      scheduledDate: "2025-06-20T16:00:00.000Z",
      durationPeriod: 15,
    },
    techStack: [],
    description: "Looking for a marketing specialist to drive social media campaigns.",
    durationLimit: 25,
    numberOfQuestions: 3,
    questions: [{ question: "Describe a successful campaign you managed.", expectedAnswer: "" }],
    invitedCandidates: [],
    createdAt: "2025-05-23T15:30:00.000Z",
    userId: "05zA4adRRvcFofNuZZooCVKbUEc2",
  },

  {
    title: "QA Engineer",
    companyName: "QualityFirst",
    companyLogo: "",
    level: "Medium",
    category: "Technical",
    type: "Coding",
    coding: true,
    completed: true,
    date: {
      interviewTimming: "future",
      avialabilityDuration: "limited",
      scheduledDate: "2025-05-28T09:30:00.000Z",
      durationPeriod: 12,
    },
    techStack: ["Selenium", "Jest"],
    description: "QA Engineer with automation testing experience required.",
    durationLimit: 30,
    numberOfQuestions: 4,
    questions: [{ question: "Explain the difference between unit and integration testing.", expectedAnswer: "" }],
    invitedCandidates: ["candidate10"],
    createdAt: "2025-05-17T10:20:00.000Z",
    userId: "K3dQ4dvgJjVkf48XyeEqSC6nmd53",
  },

  {
    title: "Customer Support",
    companyName: "HelpDeskPro",
    companyLogo: "",
    level: "Easy",
    category: "Behavioral",
    type: "Voice",
    coding: false,
    completed: false,
    date: {
      interviewTimming: "future",
      avialabilityDuration: "limited",
      scheduledDate: "2025-06-15T10:30:00.000Z",
      durationPeriod: 10,
    },
    techStack: [],
    description: "Customer support role with emphasis on communication skills.",
    durationLimit: 20,
    numberOfQuestions: 3,
    questions: [{ question: "How do you handle difficult customers?", expectedAnswer: "" }],
    invitedCandidates: [],
    createdAt: "2025-05-21T13:45:00.000Z",
    userId: "YCxeAjMS1WXKXyuxAGCMNZQcCSj2",
  },
];
